language: python
services:
  - docker

before_install:
  - docker build -t centos:centos7-1 .
  - docker run -d -it --name centos centos:centos7-1
  - test_var="TEST"

jobs:
  include:
    - stage: test
      name: test1
      script: docker exec -it centos ls -l
    - name: test2
      script:
        - ls -l
        - env
        - echo $test_var
      if: $test_var IS present
