language: python
services:
  - docker

before_install:
  - docker build -t centos:centos7-1 .
  - docker run -d -it --name centos centos:centos7-1

jobs:
  include:
    - script: docker exec -it centos ls -l
    - script: ls -l
