language: python
services:
  - docker

before_install:
  - docker build -t centos:centos7-1 .
  - docker run -d -it --name centos centos:centos7-1

before_script:
  - export test_var1="TEST"
  - export test_var2=""

jobs:
  include:
    - stage: test
      name: test1
      script: docker exec -it centos ls -l
    - name: test2
      script:
        - ls -l
        - env
        - echo $test_var
      if: env(test_var1) IS present
    - name: test3
      script:
        - echo test
      if: env(test_var2) IS present
