language: python
services:
  - docker

before_install:
  - docker build -t centos:centos7-1 .
  - docker run -d -it --name centos centos:centos7-1

jobs:
  include:
    - stage: test1
      script:
        - docker exec -it centos ls -l
        - ls
    - stage: test2
      script:
        - ls -l
